const LAUNCHES = {
  SUCCESS_FETCH: "SUCCESS_FETCH",
  ERROR_FETCH: "ERROR_FETCH",
  FETCH: "FETCH",
  HISTORY_FETCH: "HISTORY_FETCH",
  UPCOMING_FETCH: "UPCOMING_FETCH",
  IS_LOADING: "IS_LOADING",
};

export default LAUNCHES;
